#deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-server
  labels:
    apiServer: book-server-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book-api-server
  template:
    metadata:
      labels:
        app: book-api-server
    spec:
      containers:
      - name: api-server
        image: superm4n/book-api-server:v0.1.3
        ports:
        - containerPort: 8080

---
#service
apiVersion: v1
kind: Service
metadata:
  name: book-api-server
  labels:
    app: book-api-server
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 8080
  selector:
    app: book-api-server #selects the pod above