apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      rasel: hossain
  template:
    metadata:
      labels:
        rasel: hossain
    spec:
      containers:
      - name: nginx
        image: superm4n/test-app:v0.0.1
        ports:
        - containerPort: 80