apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-sts
spec:
  selector:
    matchLabels:
      app: server
  serviceName: "stateful-service"
  replicas: 3
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: superm4n/book-api-server:v0.1.3
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: stateful-service
  labels:
    service: label
spec:
  ports:
  - port: 8080
  clusterIP: None
  selector:
    app: server